def get_timezones():
    return {
        "Greenwich Mean Time (GMT+0)": "GMT+0",
        "Central European Time (GMT+1)": "GMT+1",
        "Eastern European Time (GMT+2)": "GMT+2",
        "Eastern African Time (GMT+3)": "GMT+3",
        "Moscow Standard Time (GMT+4)": "GMT+4",
        "Pakistan Standard Time (GMT+5)": "GMT+5",
        "Bangladesh Standard Time (GMT+6)": "GMT+6",
        "Indochina Time (GMT+7)": "GMT+7",
        "China Standard Time (GMT+8)": "GMT+8",
        "Japan Standard Time (GMT+9)": "GMT+9",
        "Australian Eastern Standard Time (GMT+10)": "GMT+10",
        "Solomon Islands Time (GMT+11)": "GMT+11",
        "New Zealand Standard Time (GMT+12)": "GMT+12",
        "Azores Standard Time (GMT-1)": "GMT-1",
        "Brasília Time (GMT-2)": "GMT-2",
        "Atlantic Standard Time (GMT-3)": "GMT-3",
        "Eastern Standard Time (GMT-4)": "GMT-4",
        "Central Standard Time (GMT-5)": "GMT-5",
        "Mountain Standard Time (GMT-6)": "GMT-6",
        "Pacific Standard Time (GMT-7)": "GMT-7",
        "Alaska Standard Time (GMT-8)": "GMT-8",
        "Hawaii-Aleutian Standard Time (GMT-9)": "GMT-9",
        "Samoa Standard Time (GMT-10)": "GMT-10",
        "Marquesas Time (GMT-9:30)": "GMT-9:30",
        "Niue Time (GMT-11)": "GMT-11",
        "Baker Island Time (GMT-12)": "GMT-12",
        "Australian Eastern Daylight Time (GMT+11)": "GMT+11",
    }
